### PR TITLE
Register yafowil with plone-legacy bundle to fix interfering while initializing Plone widgets.

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by rnixx** [comment]
I have no strong opinion about whether YAFOWIL resources gets delivered as own bundle or via legacy one. Did this change really fix an issue related to YAFOWIL?

**Comment by rnixx** [comment]
@jensens afairc @thet solved a problem with this PR which actually was caused by something else. please revert until it's cleanly pointed out what kind of benefit we have. thank you

**Comment by jensens** [comment]
Afair its about order, legacy is loaded after all other. We have it in 
production and it solved the problem. Imo we should keep it and if a better 
solution comes up another PR may happen. Better than keeping a state with 
using this branch successfully in now 4 projects.

Am 12. April 2018 7:28:47 nachm. schrieb Robert Niederreiter 
<notifications@github.com>:
@jensens afairc @thet solved a problem with this PR which actually was 
caused by something else. please revert until it's cleanly pointed out what 
kind of benefit we have. thank you

**Comment by rnixx** [comment]
agreed

**Comment by rnixx** [comment]
i reverted the change, legacy bundle is not loaded last. jqueryui is an addon widget dependency which registers it's own bundle, and this is actually loaded last. so we need to deliver yafowil resources after jqueryui has been loaded.

as discussed at bssp 2018, yafowil resources should be loaded on first demand, but this is out of scope now

**Pull request merged**
